### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by salamwaddah** [jadKhoury1/simple-body-validator#24] opened 2022-12-12 05:54 UTC
On a vue project when running in dev I am getting this warning.

I'm on the latest version `"simple-body-validator": "^1.2.10",`

<img width="484" alt="image" src="https://user-images.githubusercontent.com/26627088/206969887-dfe04943-1a0c-4ff5-ac13-59cacb6a9cb0.png">

**Comment by jadKhoury1** [comment] 2022-12-13 04:55
Hello Salam, the issue is fixed in version 1.2.11

**Closed** 2022-12-13 08:25 UTC
